draw_config:
  dark_mode: true
  n_columns: 2
parse_config:
  zmk_keycode_map:
    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦
    
    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →